### ISSUE TITLE
Validation Plot

### ISSUE THREAD

**Issue by gregmacfarlane** [pbsag/outviz#1]
![screen shot 2016-03-16 at 5 42 37 pm](https://cloud.githubusercontent.com/assets/2234830/13829646/7e39863c-eb9e-11e5-8e78-68dd10100abd.png)

**Comment by gregmacfarlane** [comment]
Initial plot in 51d227b18192c0391d65e29c713bb6218856b9a7

**Comment by gregmacfarlane** [comment]
would be good to put lm equations on the chart? or in a separate table?

**Comment by rickdonnelly** [comment]
Wow, I need to coordinate with you soon. I will set up time for us to connect via GoToMeeting this afternoon.

**Comment by gregmacfarlane** [comment]
I'm happy to chat whenever.
