### ISSUE TITLE
Streamline outviz with hmcr package

### ISSUE THREAD

**Issue by dkyleward** [pbsag/outviz#16]
Rework the package, including sample data, template, etc., to assume that an [hcmr](https://github.com/pbsag/hcmr) network will be used.

**Comment by gregmacfarlane** [comment]
Can you provide an example of the fields that would be in an `hcmr` network?

**Comment by dkyleward** [comment]
It looks like the important ones would be:
- Facility Type
  - Freeway
  - MLHighway
  - TLHighway
  - PrArterial
  - MinArterial
  - Collector
  - Local
- Area Type
  - Urban
  - Suburban
  - Rural

**Comment by gregmacfarlane** [comment]
I guess that it would be good to have an example that both used the hcmr definitions but that also was real, so that the images would look good. If you have one, can you send it along or fix `data-raw` yourself?

**Comment by dkyleward** [comment]
I now think this is a terrible idea.
