### ISSUE TITLE
plot_mdd color_field option and geom_smooth issue

### ISSUE THREAD

**Issue by dkyleward** [pbsag/outviz#22]
When I use the color_field option, I get multiple, smoothed lines. I'd like to be able to turn this on/off, as it can lead to a messy graph (see below). Also, I don't think I can control the ordering of the NEWFCLASS legend. I tried converting it into an ordered factor, but still shows up out of order.

![image](https://cloud.githubusercontent.com/assets/10221750/21526230/9ca13dca-ccf0-11e6-87f5-35bd8d174d67.png)

**Comment by dkyleward** [comment]
Perhaps we need to change this function to use the pass through "..." argument to ggplot2 (or a named list of ggplot2 arguments). I realized I'd like to change the MDD line to thick/red to make it stand out and possibly change the alpha/opacity values of the points. Removing the NEWFCLASS colors, my plot looks like this:

![image](https://cloud.githubusercontent.com/assets/10221750/21526422/11cab8fa-ccf2-11e6-8483-1005a8d76141.png)

**Comment by gregmacfarlane** [comment]
I'm already in the process of rewriting this function to use plotly. Also, the smoothed conditional mean lines don't really mean very much in this context so we probably just need to dump them.

**Comment by gregmacfarlane** [comment]
Dumped the stat_smooth in b5a0cdde

**Comment by gregmacfarlane** [comment]
This is closed by reconfiguring the functions and removing the smooth line.
