### ISSUE TITLE
VOC should be averaged and not summed

### ISSUE THREAD

**Issue by gregmacfarlane** [pbsag/outviz#24]
Currently we calculate the sum of the V/C ratios in a link. It seems like we should have a mean or a weighted mean instead.

```r
  } else if(type == "voc"){
    # volume-to-capacity ratio
    fn_agg <- lazyeval::interp(
      ~sum(x/y), x = as.name(volume), y = as.name(capacity))
  }
```

**Comment by gregmacfarlane** [comment]
As a note, we'll need to adjust the totals row function as well.

**Comment by gregmacfarlane** [comment]
Closed with #25

**Comment by dkyleward** [comment]
I will add that for most planning applications I've done, it's the worst V/C that people care about. I have no idea if that applies here. Just my .02

**Comment by gregmacfarlane** [comment]
That's an interesting point, though I wonder if the 85th percentile is even better. I mean, if one link (100th percentile) is heavily congested then that doesn't indicate a system failure, or even that anything should be done. But if the 85th percentile link is failing, then you may have a systemic issue.
