### ISSUE TITLE
Vehicle miles traveled table

### ISSUE THREAD

**Issue by gregmacfarlane** [pbsag/outviz#3]
![screen shot 2016-03-16 at 5 45 55 pm](https://cloud.githubusercontent.com/assets/2234830/13829772/1360371a-eb9f-11e5-9a0c-ee9df8a606b9.png)

**Comment by gregmacfarlane** [comment]
Need more information on how to do this one.

**Comment by dkyleward** [comment]
There are two ways that this is usually done.  The first, that I really dislike, is to just take the count links and multiply the volume and the count by the length of the link to get VMT and compare.

The second would be to have HPMS data to estimate total VMT for the model region.  Then compare it to the model.  [IL Example](https://www.fhwa.dot.gov/policyinformation/hpms/nahpms.cfm)

**Comment by gregmacfarlane** [comment]
Closed (using the naive solution) in 0be51e59daa9210b2215d6d2488fabca32f8abd0. The more extensive solution is outside the scope of this package for now.
